Integrirani Sistemi/Lab2/BookingApplication/Models/BookingList.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookingApplication.Models {
    public class BookingList {
        [Key]
        public Guid Id { get; set; }
        public string? OwnerId { get; set; }
        [ForeignKey("OwnerId")]
        public BookingApplicationUser? Owner { get; set; }
        public virtual ICollection<BookReservation>? BookReservations { get; set; }
    }
}

Integrirani Sistemi/Lab2/BookingApplication/Controllers/BookingListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingApplication.Data;
using BookingApplication.Models;
using System.Security.Claims;
using NuGet.Packaging;
using NuGet.Versioning;

namespace BookingApplication.Controllers
{
    public class BookingListsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingListsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult BookNow(int nights){
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if(userId == null)
                return NotFound();

            var loggedInUser = _context.Users.Where(u => u.Id == userId)
                .Include(u => u.Reservations)
                .Include(u=> u.BookingList)
                .FirstOrDefault();

            if (loggedInUser == null || loggedInUser.Reservations == null)
                return NotFound();

            var list = loggedInUser.BookingList;
            if(list == null) {

                list = new BookingList {
                    Id = Guid.NewGuid(),
                    OwnerId = userId,
                    Owner = loggedInUser,
                };
                _context.BookingLists.Add(list);
            }

            List<BookReservation> reservations = loggedInUser.Reservations
                .Select(r => new BookReservation {
                    Id = Guid.NewGuid(),
                    ReservationId = r.Id,
                    Reservation = r,
                    BookingListId = list.Id,
                    BookingList = list,
                    NumberOfNights = nights,
                }).ToList();

                
            _context.BookReservations.AddRange(reservations);
            loggedInUser.Reservations.Clear();

            _context.SaveChanges();
            

            return RedirectToAction("Index");

        }


        // GET: BookingLists
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if(userId == null)
                return NotFound();

            var loggedInUser =  _context.Users.Where(u => u.Id == userId)
                .Include(u => u.BookingList)
                .FirstOrDefault();

            if(loggedInUser == null || loggedInUser.BookingList == null)
                return NotFound();

            var list =  _context.BookingLists.Where(b => b.OwnerId == userId)
                .Include(b=>b.Owner)
                .Include(b => b.BookReservations)
                    .ThenInclude(br => br.Reservation)
                    .ThenInclude(br => br.Apartment)
                .FirstOrDefault();

            if(list == null)
                return NotFound();

            return View(list);

        }

        // GET: BookingLists/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingList = await _context.BookingLists
                .Include(b => b.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookingList == null)
            {
                return NotFound();
            }

            return View(bookingList);
        }

        // GET: Reservations/Create
        public IActionResult Create() {
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "ApartmentName");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Check_in_date,ApartmentId")] Reservation reservation, int nights) {
            if(ModelState.IsValid) {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var loggedinUser = _context.Users.Find(userId);
                reservation.User = loggedinUser;
                reservation.Id = Guid.NewGuid();
                _context.Add(reservation);
                BookingList list = _context.BookingLists.Where(u => u.OwnerId == userId).Include(r => r.BookReservations).FirstOrDefault();
                if(list == null) {

                    list = new BookingList {
                        Id = Guid.NewGuid(),
                        OwnerId = userId,
                        Owner = loggedinUser,
                    };
                    _context.BookingLists.Add(list);
                }

                BookReservation reservations = new BookReservation {
                        Id = Guid.NewGuid(),
                        ReservationId = reservation.Id,
                        Reservation = reservation,
                        BookingListId = list.Id,
                        BookingList = list,
                        NumberOfNights = nights,
                    };
                _context.BookReservations.Add(reservations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "ApartmentName", reservation.ApartmentId);
            return View(reservation);
        }

        // GET: BookingLists/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingList = await _context.BookingLists.FindAsync(id);
            if (bookingList == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_context.Users, "Id", "Id", bookingList.OwnerId);
            return View(bookingList);
        }

        // POST: BookingLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,OwnerId")] BookingList bookingList)
        {
            if (id != bookingList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookingList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingListExists(bookingList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_context.Users, "Id", "Id", bookingList.OwnerId);
            return View(bookingList);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(Guid? id) {
            if(id == null) {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Apartment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(reservation == null) {
                return NotFound();
            }
            ViewData["id"]=id;
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id) {
            var reservation = await _context.BookReservations.FindAsync(id);
            if(reservation != null) {
                _context.BookReservations.Remove(reservation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingListExists(Guid id)
        {
            return _context.BookingLists.Any(e => e.Id == id);
        }



    }
}

Integrirani Sistemi/Lab2/BookingApplication/Views/BookingLists/Create.cshtml
@model BookingApplication.Models.Reservation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Check_in_date" class="control-label"></label>
                <input asp-for="Check_in_date" class="form-control" />
                <span asp-validation-for="Check_in_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApartmentId" class="control-label"></label>
                <select asp-for="ApartmentId" class ="form-control" asp-items="ViewBag.ApartmentId"></select>
            </div>
            <div>
                <label for="nights">Number of nights</label>
                <input id="nights" name="nights" required type="number" />
                <button class="btn btn-success">Book Now</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Integrirani Sistemi/Lab2/BookingApplication/Views/BookingLists/Delete.cshtml
@model BookingApplication.Models.Reservation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Check_in_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Check_in_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apartment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apartment.ApartmentName)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@ViewData["id"]" asp-controller="BookingLists">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Integrirani Sistemi/Lab2/BookingApplication/Views/BookingLists/Details.cshtml
@model BookingApplication.Models.BookingList

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>BookingList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Integrirani Sistemi/Lab2/BookingApplication/Views/BookingLists/Edit.cshtml
@model BookingApplication.Models.BookingList

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>BookingList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Integrirani Sistemi/Lab2/BookingApplication/Views/BookingLists/Index.cshtml
@model BookingApplication.Models.BookingList

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double totalPrice = 0;
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="BookingLists">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Apartment Name
            </th>
            <th>
                Price per night
            </th>
            <th>
                Number of nights
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.BookReservations) {
            totalPrice += item.NumberOfNights * item.Reservation.Apartment.Price_per_night;
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Reservation.Apartment.ApartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reservation.Apartment.Price_per_night)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfNights)
            </td>
            <td>
                    <form asp-action="Delete" asp-route-id="@item.Id" asp-controller="BookingLists">
                        <button class="btn btn-danger">Delete</button>
                    </form>
            </td>
        </tr>
}
    </tbody>
    <tfoot>
         Total Price: @totalPrice
    </tfoot>
</table>