Integrirani Sistemi/Lab1HardVersion/Lab1.Web/Controllers/TheaterShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab1.Web.Data;
using Lab1.Web.Models.Domain;
using Lab1.Web.Models.Identity;
using System.Security.Claims;

namespace Lab1.Web.Controllers
{
    public class TheaterShowsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TheaterShowsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TheaterShows
        public async Task<IActionResult> Index()
        {
            return View(await _context.TheaterShows.ToListAsync());
        }

        // GET: TheaterShows/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theaterShow = await _context.TheaterShows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (theaterShow == null)
            {
                return NotFound();
            }

            return View(theaterShow);
        }

        // GET: TheaterShows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TheaterShows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ShowDate,Place,ImageUrl")] TheaterShow theaterShow)
        {
            if (ModelState.IsValid)
            {
                theaterShow.Id = Guid.NewGuid();
                _context.Add(theaterShow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(theaterShow);
        }

        // GET: TheaterShows/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theaterShow = await _context.TheaterShows.FindAsync(id);
            if (theaterShow == null)
            {
                return NotFound();
            }
            return View(theaterShow);
        }

        // POST: TheaterShows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Description,ShowDate,Place,ImageUrl")] TheaterShow theaterShow)
        {
            if (id != theaterShow.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(theaterShow);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TheaterShowExists(theaterShow.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(theaterShow);
        }

        // GET: TheaterShows/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theaterShow = await _context.TheaterShows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (theaterShow == null)
            {
                return NotFound();
            }

            return View(theaterShow);
        }

        // POST: TheaterShows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var theaterShow = await _context.TheaterShows.FindAsync(id);
            if (theaterShow != null)
            {
                _context.TheaterShows.Remove(theaterShow);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> BuyTicket(Guid? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var show = await _context.TheaterShows.FindAsync(id);
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);


            if (show == null || user == null) {
                return NotFound();
            }

            var loggedInUser = await _context.Users.FindAsync(user);

            Ticket ticket = new Ticket {
                Id = Guid.NewGuid(),
                TheaterShowId = show.Id,
                UserId = Guid.Parse(user),
                TheaterShow = show,
                Lab1User = loggedInUser,
                Price = -1
            };

            return View(ticket);
        }

        [HttpPost]
        public async Task<IActionResult> BuyTicketConfirmed(Ticket model) {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var loggedInUser = await _context.Users.FindAsync(userId);
            var show = await _context.TheaterShows.FindAsync(model.TheaterShowId);

            model.TheaterShow = show;
            model.Lab1User = loggedInUser;

            _context.Tickets.Add(model);
            await _context.SaveChangesAsync();

            return View("Index", await _context.TheaterShows.ToListAsync());
        }

        private bool TheaterShowExists(Guid id){
            return _context.TheaterShows.Any(e => e.Id == id);
        }
    }
}

Integrirani Sistemi/Lab1HardVersion/Lab1.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab1.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab1.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab1.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TheaterShows" asp-action="">Theater Shows</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab1.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>